# Generated by Django 3.2.2 on 2021-05-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
